spring.application.name=com.application

server.port=8081
spring.datasource.url=jdbc:mysql://localhost:3306/ecom
spring.datasource.username=root
spring.datasource.password=934349
spring.jpa.hibernate.ddl-auto=update

# for Actuator
management.endpoints.web.exposure.include=*
management.endpoint.health.show-details=always
management.info.env.enable=true
info.app.name=Myapp
info.app.description=For web

management.endpoint.shutdown.enabled=true
