spring.application.name=com.application
# Server port
server.port=8081

# Database connection
spring.datasource.url=jdbc:postgresql://localhost:5432/ecom
spring.datasource.username=postgres
spring.datasource.password=admin123
spring.datasource.driver-class-name=org.postgresql.Driver

# Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Actuator
management.endpoints.web.exposure.include=*
management.endpoint.health.show-details=always
management.info.env.enable=true
info.app.name=MyApp
info.app.description=For web

# Enable shutdown endpoint
management.endpoint.shutdown.enabled=true